version: "3"

tasks:
  unit-test:
    deps: [_direnv-allow, _unit-test-clean-cache]
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  # Internal Tasks
  _unit-test-clean-cache:
    internal: true
    cmds:
      - go clean -testcache

  _direnv-allow:
    internal: true
    cmds:
      - direnv allow
